% Compute power spectrum

% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 24-Apr-2024 21:17:29

% Parameters
timeLimits = [0 0.000819]; % seconds
frequencyLimits = [-3500000 3500000]; % Hz

%%
% Index into signal time region of interest
tx_vec_ROI = tx_vec(:);
sampleRate = 5000000; % Hz
startTime = 0; % seconds
minIdx = ceil(max((timeLimits(1)-startTime)*sampleRate,0))+1;
maxIdx = floor(min((timeLimits(2)-startTime)*sampleRate,length(tx_vec_ROI)-1))+1;
tx_vec_ROI = tx_vec_ROI(minIdx:maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[Ptx_vec_ROI, Ftx_vec_ROI] = pspectrum(tx_vec_ROI,sampleRate, ...
    'FrequencyLimits',frequencyLimits);

%%
% Index into signal time region of interest
tx_vec_iris_ROI = tx_vec_iris(:);
sampleRate = 5000000; % Hz
startTime = 0; % seconds
minIdx = ceil(max((timeLimits(1)-startTime)*sampleRate,0))+1;
maxIdx = floor(min((timeLimits(2)-startTime)*sampleRate,length(tx_vec_iris_ROI)-1))+1;
tx_vec_iris_ROI = tx_vec_iris_ROI(minIdx:maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[Ptx_vec_iris_ROI, Ftx_vec_iris_ROI] = pspectrum(tx_vec_iris_ROI,sampleRate, ...
    'FrequencyLimits',frequencyLimits);

plot(Ptx_vec_iris_ROI, Ftx_vec_iris_ROI);
